# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yey < Formula
  desc "An interactive, human-friendly docker launcher for dev and devops"
  homepage "https://github.com/silphid/yey"
  version "0.3.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/silphid/yey/releases/download/v0.3.0/yey_0.3.0_darwin_x86_64.tar.gz"
    sha256 "2650e3c0b46ef382f648e09c9cbeed96c0f53accfc5891cf84bf7e4582b115cc"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/silphid/yey/releases/download/v0.3.0/yey_0.3.0_darwin_arm64.tar.gz"
    sha256 "f48c7e1ed65326bcb205f5ab460066562739ea2283d40cccd31e148ced0ceb48"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/silphid/yey/releases/download/v0.3.0/yey_0.3.0_linux_x86_64.tar.gz"
    sha256 "eeabd80ae41850f21cd7cc9bf220d1afeeef2c791623c614abad54106c763ed1"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/silphid/yey/releases/download/v0.3.0/yey_0.3.0_linux_arm64.tar.gz"
    sha256 "d3ac33c11abbc82a6bcf5bc10d8112255d914d12e7676df72d704a71d6e05bc7"
  end

  def install
    bin.install "yey"
  end
end
