# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yey < Formula
  desc "An interactive, human-friendly docker launcher for dev and devops"
  homepage "https://github.com/silphid/yey"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/silphid/yey/releases/download/v0.1.0/yey_0.1.0_darwin_x86_64.tar.gz"
    sha256 "be5a1f77906e0d068df0e6210a93157ce90e4c8897235a09b746ebf2a8aaa244"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/silphid/yey/releases/download/v0.1.0/yey_0.1.0_darwin_arm64.tar.gz"
    sha256 "b03f5f006176ab64e7477b4949dc934ad3678df7a738d0dee05efb66e98e7eb8"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/silphid/yey/releases/download/v0.1.0/yey_0.1.0_linux_x86_64.tar.gz"
    sha256 "e0ee40d1d1de662117880a8a5c46a4c3a848a1748638691de7bb8fcdb6e328f1"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/silphid/yey/releases/download/v0.1.0/yey_0.1.0_linux_arm64.tar.gz"
    sha256 "e5b2f260bf8b2c0f17dbd0185f7e4a5bfd014236ddbc5763fa1884efa4c29c3c"
  end

  def install
    bin.install "yey"
  end
end
